# Generated by Django 5.2.6 on 2025-09-18 06:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('subtype', models.CharField(blank=True, max_length=128)),
                ('requester', models.CharField(blank=True, max_length=128)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('urgency', models.CharField(default='normal', max_length=32)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('assigned', 'Assigned'), ('in_analysis', 'In Analysis'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='registered', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('raw_meta', models.JSONField(blank=True, default=dict)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_samples', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.sampletype')),
            ],
        ),
    ]
