# Generated by Django 5.2.6 on 2025-09-30 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subtype', models.CharField(blank=True, max_length=64, null=True)),
                ('editable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatBlend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fatblends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('production_code', models.CharField(blank=True, max_length=64, null=True)),
                ('line', models.CharField(blank=True, choices=[('A', 'Line A'), ('B', 'Line B'), ('C', 'Line C'), ('D', 'Line D'), ('E', 'Line E'), ('W', 'Line W'), ('Y', 'Line Y'), ('Z', 'Line Z')], max_length=4, null=True)),
                ('additives', models.JSONField(blank=True, default=dict)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fatblend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.fatblend')),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('sample_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('fatblend', 'Fat Blend'), ('finished_product', 'Finished Product'), ('packaging', 'Packaging')], max_length=32)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_ANALYSIS', 'In Analysis'), ('IN_APPROVAL', 'In Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted')], default='REGISTERED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_meta', models.JSONField(blank=True, default=dict)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_samples', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_tank', models.CharField(choices=[('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5'), ('J6', 'J6'), ('J7', 'J7'), ('J8', 'J8'), ('J9', 'J9'), ('J10', 'J10'), ('J11', 'J11'), ('J12', 'J12'), ('J13', 'J13')], max_length=8)),
                ('to_tank', models.CharField(choices=[('TA', 'TA'), ('TB', 'TB'), ('TC', 'TC'), ('TD', 'TD'), ('TE', 'TE'), ('TF', 'TF')], max_length=8)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('transfer_no', models.PositiveIntegerField(default=1)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.rawmaterial')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transfer_date', '-transfer_no'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5'), ('J6', 'J6'), ('J7', 'J7'), ('J8', 'J8'), ('J9', 'J9'), ('J10', 'J10'), ('J11', 'J11'), ('J12', 'J12'), ('J13', 'J13'), ('TA', 'TA'), ('TB', 'TB'), ('TC', 'TC'), ('TD', 'TD'), ('TE', 'TE'), ('TF', 'TF')], max_length=8, unique=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('current_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_tank', to='samples.transferrawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='FatBlendComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fatblend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='samples.fatblend')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.tank')),
            ],
            options={
                'unique_together': {('fatblend', 'tank')},
            },
        ),
    ]
